### ISSUE TITLE
issue in ".nig" command in .exe version

### ISSUE THREAD

**Issue by slpkbt** [Vazgen005/Self-bot-by-Vazgen005#1]
command ".nig" just do nothing and throw an error in console

error:
```

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "discord\ext\commands\bot.py", line 939, in invoke
  File "discord\ext\commands\core.py", line 863, in invoke
  File "discord\ext\commands\core.py", line 94, in wrapped
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'resolved'
```

**Comment by Vazgen005** [comment]
You just use it incorrectly, i will fix it maybe :)
